Scheduler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('lesson_scheduling.urls',
                      namespace="lesson_scheduling")),
]

lesson_scheduling/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # Student
    url(r'^student/$', views.students, name="students"),
    url(r'^student/(?P<student_id>[0-9]+)/$',
        views.student, name="student"),
    # Teacher
    url(r'^teacher/(?P<teacher_id>[0-9]+)/$',
        views.teacher, name="teacher"),
    url(r'^teacher/(?P<teacher_id>[0-9]+)/schedule/$',
        views.schedule, name="schedule"),
    url(r'^teacher/(?P<teacher_id>[0-9]+)/schedule/save/$',
        views.saveSchedule, name="saveSchedule"),
    # Chamber Groups
    url(r'^chamber_groups/$', views.chambergroups, name="chamber_groups"),
    url(r'^chamber_group/(?P<chamber_group_id>[0-9]+)/$',
        views.chambergroup, name="chamber_group"),
    # Input and update
    url(r'input/$', views.dataInput, name="dataInput"),
    url(r'update/student_schedule/$',
        views.updateStudentSchedule, name="updateStudentSchedule"),
    ]

lesson_scheduling/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(null=True)

    def getName(self):
        return "{0} {1}".format(self.first_name, self.last_name)


class Student(Person):
    teacher = models.ManyToManyField("Teacher")

    def __str__(self):
        return "Student: {0}".format(self.getName())


class Teacher(Person):
    def __str__(self):
        return "Teacher: {0}".format(self.getName())


class ChamberGroup(models.Model):
    name = models.CharField(max_length=50)
    student = models.ManyToManyField("Student")
    coach = models.ManyToManyField("Teacher")

    def __str__(self):
        return "ChamberGroup: {}".format(self.name)


class Room(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return "Room: {}".format(self.name)


class Lesson(models.Model):
    teacher = models.ForeignKey("Teacher")
    room = models.ForeignKey("Room", null=True)
    date = models.DateField()
    start_time = models.TimeField()
    duration = models.SmallIntegerField(default=60)

    def __str__(self):
        return "Teacher: {}, at {},{} duration: {}"\
            .format(self.teacher.getName(), self.date, self.start_time,
                    self.duration)


class SingleStudentLesson(Lesson):
    student = models.ForeignKey("Student", null=True)


class ChamberGroupLesson(Lesson):
    chamber_group = models.ForeignKey("ChamberGroup", null=True)

lesson_scheduling/views.py
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.views import generic
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from .models import Teacher, Student, \
  SingleStudentLesson, ChamberGroupLesson
from .timeline import Period, Time
from .scheduleUtil import readScheduleForm, scheduleClasses
from .modelUtil import TeacherUtil

import datetime as dt


class IndexView(generic.ListView):
    """Show lists of teachers as the starting point of workflow.
    If there's no teacher, display a link to read the input data from csv files.
    Clicking on a teacher's name brings the user to the teacher view."""
    template_name = 'lesson_scheduling/index.html'
    context_object_name = 'teacher_list'

    def get_queryset(self):
        return TeacherUtil.getTeachers()


# TODO: Resolve CSRF issue.
@csrf_exempt
def teacher(request, teacher_id):
  from .modelUtil import getStudentsOfTeacher, getChamberGroupOfTeacher
  mTeacher = get_object_or_404(Teacher, pk=teacher_id)
  student_list = getStudentsOfTeacher(teacher_id)
  chamber_group_list = getChamberGroupOfTeacher(teacher_id)

  template = loader.get_template('lesson_scheduling/teacher.html')
  context = RequestContext(request, {
    "teacher": mTeacher,
    "student_list": student_list,
    "chamber_group_list": chamber_group_list,
  })
  return HttpResponse(template.render(context))

def students(request):
  student_list = Student.objects.order_by('last_name')
  template = loader.get_template('lesson_scheduling/students.html')
  context = RequestContext(request, {
    'student_list': student_list,
  })
  return HttpResponse(template.render(context))


def chambergroups(request):
  from .models import ChamberGroup
  group_list = ChamberGroup.objects.order_by('name')
  template = loader.get_template('lesson_scheduling/chamber_groups.html')
  context = RequestContext(request, {
    'group_list': group_list,
  })
  return HttpResponse(template.render(context))


def chambergroup(request, chamber_group_id):
  from .models import ChamberGroup
  mChamberGroup = get_object_or_404(ChamberGroup, pk=chamber_group_id)
  student_list = mChamberGroup.student.all()

  template = loader.get_template('lesson_scheduling/chamber_group.html')
  context = RequestContext(request, {
    'chamber_group': mChamberGroup,
    'student_list': student_list,
  })
  return HttpResponse(template.render(context))


def student(request, student_id):
  from .modelUtil import getStudentLessons
  from .timeline import parseLessonStartTime

  mStudent = get_object_or_404(Student, pk=student_id)
  name = mStudent.getName()
  date = dt.date.today()  # TODO: enable date
  lessons = getStudentLessons(student_id, date)
  L = []
  for lesson in lessons:
    start = parseLessonStartTime(lesson)
    end = start.plusPeriodNew(Period(lesson.duration))
    teacher_name = lesson.teacher.getName()
    L.append((teacher_name, start, end))
  template = loader.get_template('lesson_scheduling/student.html')
  context = RequestContext(request, {
    'student_name': name,
    'lesson_list': L,
  })
  return HttpResponse(template.render(context))





@csrf_exempt
def schedule(request, teacher_id):
  input_date = request.POST['date']
  input_repeat = ('repeat' in request.POST)
  input_last_date = request.POST['last_date']

  request.session['date'] = input_date
  request.session['repeat'] = input_repeat
  request.session['last_date'] = input_last_date

  dates = getDates(input_date, input_repeat, input_last_date)

  start_time = parseTime(request.POST['start_time'])
  # get data from the form
  D, calendars, ranks = readScheduleForm(request, teacher_id, dates)
  schedule_list = scheduleClasses(D, ranks, start_time, calendars)
  mTeacher = get_object_or_404(Teacher, pk=teacher_id)

  template = loader.get_template('lesson_scheduling/chooseSchedule.html')
  context = RequestContext(request, {
    "teacher": mTeacher,
    "schedule_list": schedule_list,
    "teacher_id": teacher_id,
  })
  return HttpResponse(template.render(context))


def parseDate(date_str):
  L = date_str.split("/")
  assert len(L) == 3
  mm, dd, yyyy = [int(x) for x in L]
  return dt.date(yyyy, mm, dd)


def parseTime(time_str):  # same as Time().fromString()
  L = time_str.split(":")
  assert len(L) == 2
  hh, mm = [int(x) for x in L]
  return Time(hh, mm)

def getDates(date, repeat, last_date):
  date = parseDate(date)
  dates = [date]
  if repeat:
    # add the same day of each week before the last date to dates
    last_date = parseDate(last_date)
    timedelta_week = dt.timedelta(7)
    current_date = date + timedelta_week
    while current_date <= last_date:
      dates.append(current_date)
      current_date += timedelta_week
  return dates



@csrf_exempt
def saveSchedule(request, teacher_id):
  from .modelUtil import getStudentFromId, getChamberGroupFromId
  input_date = request.session['date']
  input_repeat = request.session['repeat']
  input_last_date = request.session['last_date']
  dates = getDates(input_date, input_repeat, input_last_date)

  schedule = (request.POST['choice'][5:-6]).split("<br/>")
  for date in dates:
    for lesson in schedule:
      saveLesson(lesson, teacher_id, date)

  # Format lessons
  formatted_schedule = []
  for lesson in schedule:
    time_str = lesson[31:]
    start_time = time_str[:5]
    end_time = time_str[10:]
    if lesson[1] == "S":
      student_id = int(lesson[2:6])
      student = getStudentFromId(student_id)
      name = '{} {}'.format(student.first_name, student.last_name)
    else:
      chamber_group_id = lesson[2:6]
      chamber_group = getChamberGroupFromId(chamber_group_id)
      name = chamber_group.name
    formatted_schedule.append("{} - {} {}".format(start_time, end_time, name))

  teacher = get_object_or_404(Teacher, pk=teacher_id)

  template = loader.get_template('lesson_scheduling/schedule_saved.html')
  context = RequestContext(request, {
    "dates": dates,
    "schedule": formatted_schedule,
    "teacher": teacher,
  })
  return HttpResponse(template.render(context))


def saveLesson(lesson_str, teacher_id, date):
  start_time, duration = find_time_duration(lesson_str[31:])
  if lesson_str[1] == "S":
    student_id = int(lesson_str[2:6])
    l = SingleStudentLesson(teacher_id=teacher_id, student_id=student_id,
                date=date, start_time=start_time,
                duration=duration)
    l.save()
  elif lesson_str[1] == "C":
    chamber_group_id = int(lesson_str[2:6])
    l = ChamberGroupLesson(teacher_id=teacher_id,
                 chamber_group_id=chamber_group_id,
                 date=date, start_time=start_time,
                 duration=duration)
    l.save()


def find_time_duration(lesson_time_str):
  t1_str = lesson_time_str[:5]
  t2_str = lesson_time_str[10:]
  t1 = Time().fromString(t1_str)
  t2 = Time().fromString(t2_str)
  duration = (t2-t1).minute
  start_time = dt.time(t1.hour, t1.minute)
  return start_time, duration


def dataInput(request):
  """Populate empty database with data."""
  from .dataInput import saveStudentsFromSheet, saveTeachersFromSheet,\
    saveChamberGroupFromSheet, saveStudentScheduleFromSheet
  saveStudentsFromSheet()
  saveTeachersFromSheet()
  saveChamberGroupFromSheet()
  saveStudentScheduleFromSheet()
  return redirect("/")


def updateStudentSchedule(request):
  """Update students' college class schedule."""
  from .dataInput import saveStudentScheduleFromSheet
  from .modelUtil import getCollegeClass
  getCollegeClass().delete()  # Delete all college classes
  saveStudentScheduleFromSheet()  # Add the new version
  return redirect("/")

lesson_scheduling/templates/lesson_scheduling/chamber_group.html
<h1>Chamber Group: {{chamber_group.name}}</h1>

<ul>
{% for student in student_list %}
    <li><a href="/student/{{student.id}}/">{{student.getName}}</a></li>
{% endfor %}
</ul>
<a href="/chamber_groups/">Back to chamber group list</a>

lesson_scheduling/templates/lesson_scheduling/chamber_groups.html
<h1>Chamber Groups</h1>

{% if group_list %}
    <ul>
    {% for group in group_list %}
        <li><a href="/chamber_group/{{group.id}}/">{{ group.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no chamber group in the system.</p>
{% endif %}

lesson_scheduling/templates/lesson_scheduling/chooseSchedule.html
<style>
table {
    border-collapse: collapse;
}

table, td, th {
    border: 1px solid black;
}
</style>

<h1>Choose schedule for {{teacher.getName}}</h1>

<form action="{% url 'lesson_scheduling:saveSchedule' teacher_id %}" method="post">
{% csrf_token %}
<table style="width:50%">
{% for schedule in schedule_list %}
  <tr>
    <td>
        <input type="radio" name="choice" value="{{schedule}}" />
    </td>
    <td>{% autoescape off %}
        {{schedule}}
    {% endautoescape %}</td>
  </tr>
{% endfor %}
</table>
<input type="submit" value="SaveSchedule" />
</form>

lesson_scheduling/templates/lesson_scheduling/index.html
<table style="width:50%">
    <tr>
        <td><a href="{% url 'lesson_scheduling:index' %}">
          Teachers</a></td>
        <td><a href="{% url 'lesson_scheduling:students' %}">
          Students</a></td>
        <td><a href="{% url 'lesson_scheduling:chamber_groups' %}">
          Chamber Groups</a></td>
    </tr>
</table>

<h1>Schedule classes</h1>
{% if teacher_list %}
    <ul>
    {% for teacher in teacher_list %}
        <li><a href="{% url 'lesson_scheduling:teacher' teacher.id %}">
          {{ teacher.getName }}</a></li>
    {% endfor %}
    </ul>

    <h2>Other operation</h2>
    <p><a href="{% url 'lesson_scheduling:updateStudentSchedule' %}">
      Update students' schedule (college classes)</a></p>
{% else %}
    <p>There are no teacher in the system.</p>
    <p><a href="{% url 'lesson_scheduling:dataInput' %}">
      Read teachers and students data from csv files </a></p>
{% endif %}

lesson_scheduling/templates/lesson_scheduling/schedule_saved.html
<h1>Schedule Saved for {{teacher.getName}}</h1>

{% for date in dates %}
	{{date}} with {{teacher.getName}}
	<ul>
	{% for s in schedule %}
	    <li>{{s}}</li>
	{% endfor %}
	</ul>
{% endfor %}

<a href="/">Back to Index</a>

lesson_scheduling/templates/lesson_scheduling/student.html
<h1>Schedule for {{student_name}}</h1>

<ul>
{% for lesson in lesson_list %}
    <li>{{lesson.0}} : {{lesson.1}} --> {{lesson.2}}</li>
{% endfor %}
</ul>
<a href="/student/">Back to student list</a>

lesson_scheduling/templates/lesson_scheduling/students.html
{% if student_list %}
    <ul>
    {% for student in student_list %}
        <li><a href="/student/{{ student.id }}/">{{ student.getName }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no student in the system.</p>
{% endif %}

lesson_scheduling/templates/lesson_scheduling/teacher.html
<h1>Schedule lessons for {{teacher.getName}}</h1>

<!-- The next step of the workflow is the schedule view. -->
<form action="{% url 'lesson_scheduling:schedule' teacher.id %}" method="post">
{% csrf_token %}
<!-- The date to be scheduled. -->
Date: <input type="text", name="date", value="08/30/2015"/>
<br>
<!-- Schedule for the same day of multiple weeks together. -->
<input type="checkbox", name="repeat", value="repeat"/>
Every week until: <input type="text", name="last_date", value="08/30/2015"/>
<br>
<!-- The starting time of the classes. -->
Start time: <input type="text", name="start_time", value="09:00"/>
<br>



<hr>
<table>
<tr>
    <td>Student / Chamber Group</td>
    <td>Duration</td>
    <td>Position</td>
</tr>

{% for student in student_list %}
    <tr>
        <td>{{student.getName}}</td>
        <td><input type="text", name="durationS{{student.id}}", value="0"/></td>
        <td><input type="text", name="positionS{{student.id}}", value="0"/></td>
    </tr>
{% endfor %}
{% for chamber_group in chamber_group_list %}
    <tr>
        <td>{{chamber_group.name}}</td>
        <td><input type="text", name="durationC{{chamber_group.id}}", value="0"/></td>
        <td><input type="text", name="positionC{{chamber_group.id}}", value="0"/></td>
    </tr>
{% endfor %}

    <tr>
        <td>Break</td>
        <td><input type="text", name="durationB", value="0" /></td>
        <td><input type="text", name="positionB", value="0"/></td>
    </tr>
</table>
<input type="submit" value="schedule" />
</form>